const botaniaFlowers = [
    'hydroangeas',
    'endoflame',
    'thermalily',
    'rosa_arcana',
    'munchdew',
    'entropinnyum',
    'kekimurus',
    'gourmaryllis',
    'narslimmus',
    'spectrolus',
    'dandelifeon',
    'pure_daisy',
    'agricarnation',
    'bellethorn',
    'bubbell',
    'clayconia',
    'daffomill',
    'dreadthorn',
    'exoflame',
    'fallen_kanade',
    'heisei_dream',
    'hopperhock',
    'hyacidus',
    'jaded_amaranthus',
    'jiyuulia',
    'loonium',
    'marimorphosis',
    'medumone',
    'orechid',
    'pollidisiac',
    'rannuncarpus',
    'solegnolia',
    'spectranthemum',
    'tangleberrie',
    'tigerseye',
    'vinculotus',
    'manastar',
    'rafflowsia',
    'shulk_me_not',
    'bergamute',
    'orechid_ignem',
    'labellia',

    'bellethorn_chibi',
    'agricarnation_chibi',
    'hopperhock_chibi',
    'tangleberrie_chibi',
    'jiyuulia_chibi',
    'rannuncarpus_chibi',
    'clayconia_chibi',
    'marimorphosis_chibi',
    'bubbell_chibi',
    'solegnolia_chibi'
]

ServerEvents.recipes((event) => {
    botaniaFlowers.forEach((flower) => {
        event.shapeless(`botania:${flower}`, `botania:floating_${flower}`);
    });
});