ServerEvents.recipes((event) => {
  event.recipes.ifeu
    .precision_shapeless(
      'ifeu:creative_chance_addon',
      [
        'ifeu:sculk_gear',
        'ifeu:dragon_star_block',
        'minecraft:redstone_block',
        'ifeu:chance_addon_6',
        'ifeu:chance_addon_6',
        'ifeu:chance_addon_6',
        'ifeu:chance_addon_6',
        'ifeu:chance_addon_6',
        'ifeu:chance_addon_6',
      ],
      0.25
    )
    .id('kubejs:ifeu/creative_chance_addon');
});

ServerEvents.recipes((event) => {
  event.recipes.ifeu
    .precision_shaped(
      'custom_capacitors:ultimate_capacitor',
      [
        'avaritia:crystal_matrix',
        'ifeu:chance_addon_6',
        'avaritia:crystal_matrix',
        'avaritia:crystal_matrix_ingot',
        'custom_capacitors:fast_capacitor',
        'avaritia:crystal_matrix_ingot',
        'custom_capacitors:fast_capacitor',
        'avaritia:crystal_matrix_ingot',
        'custom_capacitors:fast_capacitor',
      ],
      0.10
    )
    .id('kubejs:ifeu/ultimate_capacitor');
});