ServerEvents.recipes((event) => {
  //======= Ultimate Singularity =======
  event
    .custom({
      type: 'extendedcrafting:shapeless_table',
      ingredients: [
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:lapis_lazuli"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:prosperity_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:rose_gold_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:signalum_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:redstone_alloy_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:crystal_matrix_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:unobtainium_allthemodium_alloy_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:sculk_alloy_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:dragonsteel_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:electrum"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:netherite_gold_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:nickel"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:soulium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ingot_refined_obsidian"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:elementium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:dimensional_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:copper"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ingot_osmium"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:twinite_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:iron"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:steel"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:enderium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:netherite_iron_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:silver"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:pink_slime_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:bronze"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:fiery_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:awakened_supremium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:diamond"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ethereal_spirit"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:black_iron_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:end_steel_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:vibranium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:coal"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:allthemodium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:tough_alloy_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:lithium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:netherite_emerald_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:sky_steel_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:aluminum"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:unobtainium_vibranium_alloy_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:invar"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:glowstone"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:supremium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:imperium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:gunpowder"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:netherite_diamond_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:tertium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:awakened_draconium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:netherite_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:enhanced_gold"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:stainless_steel_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:tin"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:lumium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:manasteel_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ingot_iron_compressed"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:inferium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:abyssal_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ingot_refined_glowstone"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:knightmetal_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:platinum"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:enhanced_netherite"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:gold"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:flux_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:prismalium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:iridium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:redstone_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:prudentium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:dark_metal_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:manyullyn_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:shellite_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ironwood_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:draconium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:soul_infused_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:ender_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:unobtainium_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:enhanced_iron"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:enhanced_ender_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:lead"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:extreme_ingot"}',
        },
        {
          type: 'forge:nbt',
          item: 'extendedcrafting:singularity',
          count: 1,
          nbt: '{Id:"extendedcrafting:brass_ingot"}',
        },
      ],
      result: { item: 'extendedcrafting:ultimate_singularity' },
    })
    .id(`extendedcrafting/ultimate_singularity`);
});
