ServerEvents.recipes((event) => {
  const recipes = [
    {
      base_block: 'minecraft:cyan_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_cyan',
        'chisel_chipped_integration:carpet_llama_cyan',
      ],
    },
    {
      base_block: 'minecraft:green_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_green',
        'chisel_chipped_integration:wool_llama_green',
      ],
    },
    {
      base_block: 'minecraft:emerald_block',
      other_blocks: [
        'chisel_chipped_integration:gem_emerald_bismuth',
        'chisel_chipped_integration:gem_emerald_cell',
        'chisel_chipped_integration:gem_emerald_circular',
        'chisel_chipped_integration:gem_emerald_cobble',
        'chisel_chipped_integration:gem_emerald_gold_encrusted',
        'chisel_chipped_integration:gem_emerald_masonry',
        'chisel_chipped_integration:gem_emerald_ornate',
        'chisel_chipped_integration:gem_emerald_ornate_tiles',
        'chisel_chipped_integration:gem_emerald_panel',
        'chisel_chipped_integration:gem_emerald_prism',
        'chisel_chipped_integration:gem_emerald_smooth',
        'chisel_chipped_integration:gem_emerald_tile',
        'chisel_chipped_integration:gem_emerald_tiles',
        'chisel_chipped_integration:gem_emerald_zelda',
      ],
    },
    {
      base_block: 'minecraft:cyan_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_cyan',
        'chisel_chipped_integration:wool_llama_cyan',
      ],
    },
    {
      base_block: 'minecraft:white_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_white',
        'chisel_chipped_integration:carpet_llama_white',
      ],
    },
    {
      base_block: 'minecraft:pink_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_pink',
        'chisel_chipped_integration:wool_llama_pink',
      ],
    },
    {
      base_block: 'minecraft:red_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_red',
        'chisel_chipped_integration:carpet_llama_red',
      ],
    },
    {
      base_block: 'minecraft:gray_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_gray',
        'chisel_chipped_integration:carpet_llama_gray',
      ],
    },
    {
      base_block: 'minecraft:red_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_red',
        'chisel_chipped_integration:wool_llama_red',
      ],
    },
    {
      base_block: 'minecraft:black_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_black',
        'chisel_chipped_integration:carpet_llama_black',
      ],
    },
    {
      base_block: 'minecraft:yellow_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_yellow',
        'chisel_chipped_integration:carpet_llama_yellow',
      ],
    },
    {
      base_block: 'minecraft:gold_block',
      other_blocks: [
        'chisel_chipped_integration:metal_gold_bolted',
        'chisel_chipped_integration:metal_gold_caution',
        'chisel_chipped_integration:metal_gold_egregious',
        'chisel_chipped_integration:metal_gold_industrial_relic',
        'chisel_chipped_integration:metal_gold_scaffold',
        'chisel_chipped_integration:metal_gold_shipping_crate',
        'chisel_chipped_integration:metal_gold_thermal',
      ],
    },
    {
      base_block: 'minecraft:pink_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_pink',
        'chisel_chipped_integration:carpet_llama_pink',
      ],
    },
    {
      base_block: 'minecraft:purple_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_purple',
        'chisel_chipped_integration:wool_llama_purple',
      ],
    },
    {
      base_block: 'minecraft:brown_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_brown',
        'chisel_chipped_integration:carpet_llama_brown',
      ],
    },
    {
      base_block: 'minecraft:lime_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_lime',
        'chisel_chipped_integration:carpet_llama_lime',
      ],
    },
    {
      base_block: 'minecraft:iron_block',
      other_blocks: [
        'chisel_chipped_integration:metal_iron_bolted',
        'chisel_chipped_integration:metal_iron_caution',
        'chisel_chipped_integration:metal_iron_egregious',
        'chisel_chipped_integration:metal_iron_industrial_relic',
        'chisel_chipped_integration:metal_iron_scaffold',
        'chisel_chipped_integration:metal_iron_shipping_crate',
        'chisel_chipped_integration:metal_iron_thermal',
      ],
    },
    {
      base_block: 'minecraft:gray_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_gray',
        'chisel_chipped_integration:wool_llama_gray',
      ],
    },
    {
      base_block: 'minecraft:yellow_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_yellow',
        'chisel_chipped_integration:wool_llama_yellow',
      ],
    },
    {
      base_block: 'minecraft:purple_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_purple',
        'chisel_chipped_integration:carpet_llama_purple',
      ],
    },
    {
      base_block: 'minecraft:lapis_block',
      other_blocks: [
        'chisel_chipped_integration:gem_lapis_cobble',
        'chisel_chipped_integration:gem_lapis_gold_encrusted',
        'chisel_chipped_integration:gem_lapis_masonry',
        'chisel_chipped_integration:gem_lapis_panel',
        'chisel_chipped_integration:gem_lapis_shiny_tile',
        'chisel_chipped_integration:gem_lapis_smooth',
        'chisel_chipped_integration:gem_lapis_tile',
        'chisel_chipped_integration:gem_lapis_wood_framed',
        'chisel_chipped_integration:gem_lapis_zelda',
      ],
    },
    {
      base_block: 'minecraft:white_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_white',
        'chisel_chipped_integration:wool_llama_white',
      ],
    },
    {
      base_block: 'minecraft:brown_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_brown',
        'chisel_chipped_integration:wool_llama_brown',
      ],
    },
    {
      base_block: 'minecraft:lime_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_lime',
        'chisel_chipped_integration:wool_llama_lime',
      ],
    },
    {
      base_block: 'minecraft:diamond_block',
      other_blocks: [
        'chisel_chipped_integration:gem_diamond_bismuth',
        'chisel_chipped_integration:gem_diamond_cells',
        'chisel_chipped_integration:gem_diamond_crushed',
        'chisel_chipped_integration:gem_diamond_embossed',
        'chisel_chipped_integration:gem_diamond_gem',
        'chisel_chipped_integration:gem_diamond_gold_encrusted',
        'chisel_chipped_integration:gem_diamond_ornate_tiles',
        'chisel_chipped_integration:gem_diamond_simple',
        'chisel_chipped_integration:gem_diamond_purple_space',
        'chisel_chipped_integration:gem_diamond_space',
        'chisel_chipped_integration:gem_diamond_tiles',
        'chisel_chipped_integration:gem_diamond_zelda',
      ],
    },
    {
      base_block: 'minecraft:light_blue_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_light_blue',
        'chisel_chipped_integration:carpet_llama_light_blue',
      ],
    },
    {
      base_block: 'minecraft:light_blue_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_light_blue',
        'chisel_chipped_integration:wool_llama_light_blue',
      ],
    },
    {
      base_block: 'minecraft:redstone_block',
      other_blocks: [
        'chisel_chipped_integration:gem_redstone_arrayed_bricks',
        'chisel_chipped_integration:gem_redstone_big_tile',
        'chisel_chipped_integration:gem_redstone_braid',
        'chisel_chipped_integration:gem_redstone_bricks',
        'chisel_chipped_integration:gem_redstone_circular',
        'chisel_chipped_integration:gem_redstone_cracked',
        'chisel_chipped_integration:gem_redstone_cracked_bricks',
        'chisel_chipped_integration:gem_redstone_dent',
        'chisel_chipped_integration:gem_redstone_disordered_tiles',
        'chisel_chipped_integration:gem_redstone_encased_bricks',
        'chisel_chipped_integration:gem_redstone_french_1',
        'chisel_chipped_integration:gem_redstone_french_2',
        'chisel_chipped_integration:gem_redstone_jellybean',
        'chisel_chipped_integration:gem_redstone_layers',
        'chisel_chipped_integration:gem_redstone_mosaic',
        'chisel_chipped_integration:gem_redstone_ornate',
        'chisel_chipped_integration:gem_redstone_panel',
        'chisel_chipped_integration:gem_redstone_pillar',
        'chisel_chipped_integration:gem_redstone_prism',
        'chisel_chipped_integration:gem_redstone_road',
        'chisel_chipped_integration:gem_redstone_slanted',
        'chisel_chipped_integration:gem_redstone_small_bricks',
        'chisel_chipped_integration:gem_redstone_small_disordered_tiles',
        'chisel_chipped_integration:gem_redstone_small_tiles',
        'chisel_chipped_integration:gem_redstone_tiles',
        'chisel_chipped_integration:gem_redstone_twisted',
        'chisel_chipped_integration:gem_redstone_weathered_bricks',
        'chisel_chipped_integration:gem_redstone_wide_bricks',
      ],
    },
    {
      base_block: 'minecraft:orange_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_orange',
        'chisel_chipped_integration:wool_llama_orange',
      ],
    },
    {
      base_block: 'minecraft:orange_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_orange',
        'chisel_chipped_integration:carpet_llama_orange',
      ],
    },
    {
      base_block: 'minecraft:green_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_green',
        'chisel_chipped_integration:carpet_llama_green',
      ],
    },
    {
      base_block: 'minecraft:blue_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_blue',
        'chisel_chipped_integration:wool_llama_blue',
      ],
    },
    {
      base_block: 'minecraft:magenta_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_magenta',
        'chisel_chipped_integration:carpet_llama_magenta',
      ],
    },
    {
      base_block: 'minecraft:magenta_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_magenta',
        'chisel_chipped_integration:wool_llama_magenta',
      ],
    },
    {
      base_block: 'minecraft:light_gray_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_light_gray',
        'chisel_chipped_integration:carpet_llama_light_gray',
      ],
    },
    {
      base_block: 'minecraft:blue_carpet',
      other_blocks: [
        'chisel_chipped_integration:carpet_legacy_blue',
        'chisel_chipped_integration:carpet_llama_blue',
      ],
    },
    {
      base_block: 'minecraft:black_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_black',
        'chisel_chipped_integration:wool_llama_black',
      ],
    },
    {
      base_block: 'minecraft:light_gray_wool',
      other_blocks: [
        'chisel_chipped_integration:wool_legacy_light_gray',
        'chisel_chipped_integration:wool_llama_light_gray',
      ],
    },
    {
      base_block: 'chisel_chipped_integration:futura_gray_screen',
      other_blocks: [
        'chisel_chipped_integration:futura_cyan_screen',
        'chisel_chipped_integration:futura_me_controller',
        'chisel_chipped_integration:futura_rainbowliciously_wavy',
        'chisel_chipped_integration:futura_purple_me_controller',
        'chisel_chipped_integration:futura_fabulously_wavy',
        'chisel_chipped_integration:futura_me_controller_ae_2',
        'chisel_chipped_integration:futura_mysterious_cube',
      ],
    },
    {
      base_block: 'thermal:steel_block',
      other_blocks: [
        'chisel_chipped_integration:metal_steel_bolted',
        'chisel_chipped_integration:metal_steel_caution',
        'chisel_chipped_integration:metal_steel_egregious',
        'chisel_chipped_integration:metal_steel_industrial_relic',
        'chisel_chipped_integration:metal_steel_scaffold',
        'chisel_chipped_integration:metal_steel_shipping_crate',
        'chisel_chipped_integration:metal_steel_thermal',
        'alltheores:steel_block',
        'mekanism:block_steel',
        'common_ore_library:steel_block',
        'nuclearcraft:steel_block',
      ],
    },
    {
      base_block: 'chisel_chipped_integration:laboratory_white_panel',
      other_blocks: [
        'chisel_chipped_integration:laboratory_checkered_tiles',
        'chisel_chipped_integration:laboratory_colsole',
        'chisel_chipped_integration:laboratory_dark_medium_tiles',
        'chisel_chipped_integration:laboratory_dotted_panel',
        'chisel_chipped_integration:laboratory_fuzzy_screen',
        'chisel_chipped_integration:laboratory_large_steel',
        'chisel_chipped_integration:laboratory_large_tiles',
        'chisel_chipped_integration:laboratory_left_faced_arrows',
        'chisel_chipped_integration:laboratory_medium_tiles',
        'chisel_chipped_integration:laboratory_right_faced_arrows',
        'chisel_chipped_integration:laboratory_roundel',
        'chisel_chipped_integration:laboratory_screen',
        'chisel_chipped_integration:laboratory_small_steel',
        'chisel_chipped_integration:laboratory_tiles',
        'chisel_chipped_integration:laboratory_vents',
      ],
    },
    {
      base_block: 'thermal:bronze_block',
      other_blocks: [
        'chisel_chipped_integration:metal_bronze_bolted',
        'chisel_chipped_integration:metal_bronze_caution',
        'chisel_chipped_integration:metal_bronze_egregious',
        'chisel_chipped_integration:metal_bronze_industrial_relic',
        'chisel_chipped_integration:metal_bronze_scaffold',
        'chisel_chipped_integration:metal_bronze_shipping_crate',
        'chisel_chipped_integration:metal_bronze_thermal',
        'alltheores:bronze_block',
        'mekanism:block_bronze',
        'common_ore_library:bronze_block',
        'nuclearcraft:bronze_block',
      ],
    },
    {
      base_block: 'minecraft:copper_block',
      other_blocks: [
        'chisel_chipped_integration:metal_copper_bolted',
        'chisel_chipped_integration:metal_copper_caution',
        'chisel_chipped_integration:metal_copper_egregious',
        'chisel_chipped_integration:metal_copper_industrial_relic',
        'chisel_chipped_integration:metal_copper_scaffold',
        'chisel_chipped_integration:metal_copper_shipping_crate',
        'chisel_chipped_integration:metal_copper_thermal',
      ],
    },
    {
      base_block: 'chisel_chipped_integration:technical_caution_framed_plates',
      other_blocks: [
        'chisel_chipped_integration:technical_cables',
        'chisel_chipped_integration:technical_extremely_corroded_panels',
        'chisel_chipped_integration:technical_insulation',
        'chisel_chipped_integration:technical_megacell',
        'chisel_chipped_integration:technical_still_fan',
        'chisel_chipped_integration:technical_sturdy',
        'chisel_chipped_integration:technical_old_vent',
        'chisel_chipped_integration:technical_large_pipes',
        'chisel_chipped_integration:technical_extremely_rusted_panels',
        'chisel_chipped_integration:technical_transparent_fan',
        'chisel_chipped_integration:technical_pipes',
        'chisel_chipped_integration:technical_large_rusty_scaffold',
        'chisel_chipped_integration:technical_fan',
        'chisel_chipped_integration:technical_engineering_pipes_0',
        'chisel_chipped_integration:technical_engineering_pipes_1',
        'chisel_chipped_integration:technical_gears',
        'chisel_chipped_integration:technical_make_shift_plating',
        'chisel_chipped_integration:technical_engineering_pipes_2',
        'chisel_chipped_integration:technical_engineering_pipes_3',
        'chisel_chipped_integration:technical_exhaust_plating',
        'chisel_chipped_integration:technical_grate',
        'chisel_chipped_integration:technical_glowing_vent',
        'chisel_chipped_integration:technical_industrial_relic',
        'chisel_chipped_integration:technical_massive_hexagonal_plating',
        'chisel_chipped_integration:technical_massive_fan',
        'chisel_chipped_integration:technical_malfunction_fan',
        'chisel_chipped_integration:technical_rusty_bolted_plates',
        'chisel_chipped_integration:technical_rusty_grate',
        'chisel_chipped_integration:technical_rusty_scaffold',
        'chisel_chipped_integration:technical_small_pipes',
        'chisel_chipped_integration:technical_vent',
        'chisel_chipped_integration:technical_transparent_rusty_scaffold',
        'chisel_chipped_integration:technical_transparent_still_fan',
      ],
    },
    {
      base_block: 'mekanism:block_uranium',
      other_blocks: [
        'chisel_chipped_integration:metal_uranium_bolted',
        'chisel_chipped_integration:metal_uranium_caution',
        'chisel_chipped_integration:metal_uranium_egregious',
        'chisel_chipped_integration:metal_uranium_industrial_relic',
        'chisel_chipped_integration:metal_uranium_scaffold',
        'chisel_chipped_integration:metal_uranium_shipping_crate',
        'chisel_chipped_integration:metal_uranium_thermal',
        'alltheores:uranium_block',
        'common_ore_library:uranium_block',
        'nuclearcraft:uranium_block',
      ],
    },
    {
      base_block: 'common_ore_library:platinum_block',
      other_blocks: [
        'chisel_chipped_integration:metal_platinum_bolted',
        'chisel_chipped_integration:metal_platinum_caution',
        'chisel_chipped_integration:metal_platinum_egregious',
        'chisel_chipped_integration:metal_platinum_industrial_relic',
        'chisel_chipped_integration:metal_platinum_scaffold',
        'chisel_chipped_integration:metal_platinum_shipping_crate',
        'chisel_chipped_integration:metal_platinum_thermal',
        'alltheores:platinum_block',
        'nuclearcraft:platinum_block',
      ],
    },
    {
      base_block: 'alltheores:tin_block',
      other_blocks: [
        'chisel_chipped_integration:metal_tin_bolted',
        'chisel_chipped_integration:metal_tin_caution',
        'chisel_chipped_integration:metal_tin_egregious',
        'chisel_chipped_integration:metal_tin_industrial_relic',
        'chisel_chipped_integration:metal_tin_scaffold',
        'chisel_chipped_integration:metal_tin_shipping_crate',
        'chisel_chipped_integration:metal_tin_thermal',
        'mekanism:block_tin',
        'common_ore_library:tin_block',
        'nuclearcraft:tin_block',
        'thermal:tin_block',
      ],
    },
    {
      base_block: 'common_ore_library:aluminum_block',
      other_blocks: [
        'chisel_chipped_integration:metal_aluminum_bolted',
        'chisel_chipped_integration:metal_aluminum_caution',
        'chisel_chipped_integration:metal_aluminum_egregious',
        'chisel_chipped_integration:metal_aluminum_industrial_relic',
        'chisel_chipped_integration:metal_aluminum_scaffold',
        'chisel_chipped_integration:metal_aluminum_shipping_crate',
        'chisel_chipped_integration:metal_aluminum_thermal',
        'alltheores:aluminum_block',
        'nuclearcraft:aluminum_block',
      ],
    },
    {
      base_block: 'chisel_chipped_integration:tyrian_disordered_metal_bits',
      other_blocks: [
        'chisel_chipped_integration:tyrian_black_scaled_plates',
        'chisel_chipped_integration:tyrian_black_strips',
        'chisel_chipped_integration:tyrian_blue_plates',
        'chisel_chipped_integration:tyrian_dent',
        'chisel_chipped_integration:tyrian_diagonal_plates',
        'chisel_chipped_integration:tyrian_disordered_metal_bits',
        'chisel_chipped_integration:tyrian_disordered_purple_bits',
        'chisel_chipped_integration:tyrian_metal_plates',
        'chisel_chipped_integration:tyrian_opening',
        'chisel_chipped_integration:tyrian_platform',
        'chisel_chipped_integration:tyrian_purple_plates',
        'chisel_chipped_integration:tyrian_routes',
        'chisel_chipped_integration:tyrian_rust',
        'chisel_chipped_integration:tyrian_shiny_plate',
        'chisel_chipped_integration:tyrian_shiny_plates',
        'chisel_chipped_integration:tyrian_small_uneven_tiles',
      ],
    },
    {
      base_block: 'thermal:nickel_block',
      other_blocks: [
        'chisel_chipped_integration:metal_nickel_bolted',
        'chisel_chipped_integration:metal_nickel_caution',
        'chisel_chipped_integration:metal_nickel_egregious',
        'chisel_chipped_integration:metal_nickel_industrial_relic',
        'chisel_chipped_integration:metal_nickel_scaffold',
        'chisel_chipped_integration:metal_nickel_shipping_crate',
        'chisel_chipped_integration:metal_nickel_thermal',
        'alltheores:nickel_block',
        'common_ore_library:nickel_block',
      ],
    },
    {
      base_block: 'chisel_chipped_integration:factory_dotted_rusty_plate',
      other_blocks: [
        'chisel_chipped_integration:factory_blue_framed_circuit',
        'chisel_chipped_integration:factory_blue_circuits',
        'chisel_chipped_integration:factory_blue_wireframe',
        'chisel_chipped_integration:factory_circuit',
        'chisel_chipped_integration:factory_gold_framed_purple_plates',
        'chisel_chipped_integration:factory_gold_plated_circuit',
        'chisel_chipped_integration:factory_grinder',
        'chisel_chipped_integration:factory_ice_ice_ice',
        'chisel_chipped_integration:factory_metalbox',
        'chisel_chipped_integration:factory_metal_column',
        'chisel_chipped_integration:factory_old_vents',
        'chisel_chipped_integration:factory_orange_white_caution_stripes',
        'chisel_chipped_integration:factory_purple_wireframe',
        'chisel_chipped_integration:factory_rusty_plate',
        'chisel_chipped_integration:factory_segmented_rusty_plates',
        'chisel_chipped_integration:factory_slighly_rusty_plate',
        'chisel_chipped_integration:factory_vents',
        'chisel_chipped_integration:factory_very_rusty_plate',
        'chisel_chipped_integration:factory_wireframe',
        'chisel_chipped_integration:factory_yellow_black_caution_stripes',
      ],
    },
    {
      base_block: 'thermal:electrum_block',
      other_blocks: [
        'chisel_chipped_integration:metal_electrum_bolted',
        'chisel_chipped_integration:metal_electrum_caution',
        'chisel_chipped_integration:metal_electrum_egregious',
        'chisel_chipped_integration:metal_electrum_industrial_relic',
        'chisel_chipped_integration:metal_electrum_scaffold',
        'chisel_chipped_integration:metal_electrum_shipping_crate',
        'chisel_chipped_integration:metal_electrum_thermal',
        'alltheores:electrum_block',
        'common_ore_library:electrum_block',
        'nuclearcraft:electrum_block',
      ],
    },
    {
      base_block: 'thermal:silver_block',
      other_blocks: [
        'chisel_chipped_integration:metal_silver_bolted',
        'chisel_chipped_integration:metal_silver_caution',
        'chisel_chipped_integration:metal_silver_egregious',
        'chisel_chipped_integration:metal_silver_industrial_relic',
        'chisel_chipped_integration:metal_silver_scaffold',
        'chisel_chipped_integration:metal_silver_shipping_crate',
        'chisel_chipped_integration:metal_silver_thermal',
        'alltheores:silver_block',
        'common_ore_library:silver_block',
        'nuclearcraft:silver_block',
      ],
    },
    {
      base_block: 'thermal:lead_block',
      other_blocks: [
        'chisel_chipped_integration:metal_lead_bolted',
        'chisel_chipped_integration:metal_lead_caution',
        'chisel_chipped_integration:metal_lead_egregious',
        'chisel_chipped_integration:metal_lead_industrial_relic',
        'chisel_chipped_integration:metal_lead_scaffold',
        'chisel_chipped_integration:metal_lead_shipping_crate',
        'chisel_chipped_integration:metal_lead_thermal',
        'alltheores:lead_block',
        'mekanism:block_lead',
        'common_ore_library:lead_block',
        'nuclearcraft:lead_block',
      ],
    },
    {
      base_block: 'thermal:invar_block',
      other_blocks: [
        'chisel_chipped_integration:metal_invar_bolted',
        'chisel_chipped_integration:metal_invar_caution',
        'chisel_chipped_integration:metal_invar_egregious',
        'chisel_chipped_integration:metal_invar_industrial_relic',
        'chisel_chipped_integration:metal_invar_scaffold',
        'chisel_chipped_integration:metal_invar_shipping_crate',
        'chisel_chipped_integration:metal_invar_thermal',
        'alltheores:invar_block',
        'common_ore_library:invar_block',
      ],
    },
    {
      base_block: 'common_ore_library:cobalt_block',
      other_blocks: [
        'chisel_chipped_integration:metal_cobalt_bolted',
        'chisel_chipped_integration:metal_cobalt_caution',
        'chisel_chipped_integration:metal_cobalt_egregious',
        'chisel_chipped_integration:metal_cobalt_industrial_relic',
        'chisel_chipped_integration:metal_cobalt_scaffold',
        'chisel_chipped_integration:metal_cobalt_shipping_crate',
        'chisel_chipped_integration:metal_cobalt_thermal',
        'nuclearcraft:cobalt_block',
      ],
    },
  ];

  recipes.forEach((object) => {
    object.other_blocks.forEach((other_block) => {
      event.stonecutting(other_block, object.base_block);
      event.stonecutting(object.base_block, other_block);
    });
  });
});
